# PyNMR Config file, YAML
---
channels:    
    Deuteron5T:
        name: Deuteron5T
        species: deuteron
        cent_freq: 32.7       
        mod_freq: 400.0        
        power: 200.0      
        sweep_file: tri   
    Deuteron5T-250mV:
        name: Deuteron5T-250mV
        species: deuteron
        cent_freq: 32.7       
        mod_freq: 400.0        
        power: 250.0      
        sweep_file: tri 
    Deuteron5T-300mV:
        name: Deuteron5T-300mV
        species: deuteron
        cent_freq: 32.7       
        mod_freq: 400.0        
        power: 300.0      
        sweep_file: tri 
    Deuteron5T-350mV:
        name: Deuteron5T-350mV
        species: deuteron
        cent_freq: 32.7       
        mod_freq: 400.0        
        power: 350.0      
        sweep_file: tri 
    Deuteron5T-400mV:
        name: Deuteron5T-400mV
        species: deuteron
        cent_freq: 32.7       
        mod_freq: 400.0        
        power: 400.0      
        sweep_file: tri    
    Deuteron35MHz:
        name: Deuteron35MHz
        species: deuteron
        cent_freq: 35      
        mod_freq: 400.0        
        power: 200.0      
        sweep_file: tri 
    Deuteron38MHz:
        name: Deuteron38MHz
        species: deuteron
        cent_freq: 38      
        mod_freq: 400.0        
        power: 200.0      
        sweep_file: tri 
   
    Deuteron37MHz:
        name: Deuteron37MHz
        species: deuteron
        cent_freq: 37      
        mod_freq: 400.0        
        power: 200.0      
        sweep_file: tri 
   
settings:
    default_channel: Deuteron5T     # Default from channels listed above
    daq_type: FPGA             # Select DAQ mode (FPGA, NIDAQ or Test)
    test_signal: app/d_signal_event.txt  # signal to use for test mode
    event_dir: data-d             # Directory to put eventfiles in, relative to main.py or absolute
    te_dir: te                  # Directory to put te files in, relative to main.py or absolute
    log_dir: log                # Directory to put log files in, relative to main.py or absolute
    ss_dir: screens               # Directory to put screenshots files in, screenshots not taken if False
    steps: 512                  # Frequency points per sweep (must match for test sweeps, set to 512 otherwise)
    num_per_chunk: 64           # Number of sweeps per chunk (IntSweepCycle from FPGA manual)
    tune_per_chunk:  32         # Number of sweeps per chunk to take in tune mode
    epics_settings:
        epics_enable: true         # If false, doesn't attempt to contact EPICS server
        monitor_time: 5            # Time between calls to get EPICS data
        epics_temp: TGT:PT12:VaporPressure_T     # EPICS channel of temp to use as default 
    fpga_settings:    
        ip: 129.57.160.2        # Device IP address (str)
        port: 1028              # Device port  (int)
        tcp_buffer: 1460        # Default TCP buffer size  (int)
        dwell: 10               # Settle time in usec between frequency switch and ADC read (int) (was 10)
        per_point: 2            # Samples taken and averaged at each frequency point of a sweep (int)
        timeout_run: 20         # TCP timeout for running sweeps
        timeout_tune: 1         # TCP timeout for tune
        timeout_check: 1        # TCP timeout for check
        timeout_udp: 1          # Timeout for udp commands
        adc_drate1: true        # ADC data rate settings, see manual
        adc_drate0: true
        adc_fpath: false        # ADC fpath setting, see manual
        phase_cal: 211692085    # Conversion int to divide phase ADC values by to get max of 1
        diode_cal: 829421       # Conversion int to divide diode ADC values by to get max of 1
        test_freqs: false       # Send test frequencies to FPGA
        adc_test: false         # ADC test mode flag
    nidaq_settings:
        phase_chan: Dev1/ai0
        diode_chan: Dev1/ai1
        ao_chan: Dev1/ao0
        pretris: 10             # Number of pretriangles
        time_per_pt: 29         # Dwell time at frequency, usecs
        settling_ratio: 0.5     # Where in the dwell time the read occurs (0 to 1)     
    RS_settings:
        ip: 129.57.160.3              # R&S RF generator IP
        port: 5025 
        timeout: 2              # Telnet timeout in secs
    uWave_settings:
        enable: true         # Turn on uWave controls
        monitor_time: .4         # How long to wait between reading frequency when on monitor in s
        counter:
            ip: 129.57.160.5       # GPIB IP
            port: 1234
            timeout: 4              # Telnet timeout in secs
            addr: 19        # EIP 588C frequency counter GPIB address
            cent_freq: 140.0        # Microwave counter center frequency in GHz
            band: 3                 # Microwave counter band
            subband: 8              # Microwwave counter subband
            rate: 1000               # Counter sample rate in ms
        power_meter:
            ip: 129.57.160.11       # Serial interface IP
            port: 23
            timeout: 2              # Telnet timeout in secs
            freq: 140               # Power meter set freq in GHz
        lj-ip: 129.57.160.6     # LabJack device IP, 129.57.37.33 is pt-labjack1
    temp_settings:
        enable: false           # Turn on or off temp monitor tab
        ip: 129.57.160.8       # R&S supply IP 
        monitor_time: 60       # seconds  
    shim_settings:
        enable: true
        ip: 129.57.160.4       # R&S supply IP
        port: 5025 
        timeout: 2  
        line_resistance: 0.3     # Ohms
    fm_settings:
        enable: true
        ip: 129.57.160.12       # R&S supply IP
        port: 1234
        timeout: 2     
        addr: 10                # GPIB address    
    analysis:
        base_def: 0             # index of default baseline subtraction method      
        sub_def: 0              # index of default fit subtraction method   
        res_def: 0              # index of default results analysis method   
        wings:                  # default bounds for fit wings, must be four numbers between 0 and 1
            - 0.01
            - 0.30
            - 0.70
            - 0.99
        sum_range:              # default bounds for range integration option
            - 0.35
            - 0.65
        d_fit_params:           # initial parameters for Dulya fits
            A : 0.03
            G : -0.003
            r : 0.99
            wQ : 0.025
            wL : 31.83
            eta : 0.09
            xi : -0.1
epics_reads:                    # EPICS channels to read: key is channel name, value is string to display
    TGT:PT12:Bath_LL: Bath Level
    TGT:PT12:VaporPressure_T: Vapor Temp (K)
    TGT:PT12:Bath_Top_T: Bath Top (K)
    TGT:PT12:Bath_Bottom_T: Bath Bottom (K)
    TGT:PT12:NMR_T: Tank Temp (K)
    TGT:PT12:Bath_HTR_lvl: Bath Heater
    TGT:PT12:Fridge_F: Main Flow (slpm)
    TGT:PT12:Separator_F: Sep Flow (slpm)
    B_SOL:MPS:I_ZFCT: Solenoid Current (A)
    #posit: Target Position
epics_writes:                   # Dict of channels to write, key is channel, value is attribute of Event class 
    TGT:PT12:Polarization: pol 
    TGT:PT12:NMR_Area: area
    TGT:PT12:NMR_CC: cc
    TGT:PT12:NMR_Time: stop_stamp  
    TGT:PT12:uwave_Freq: uwave_freq
    TGT:PT12:uwave_Power: uwave_power
...
