# PyNMR Config file, YAML
---
channels:    
    Proton5T:
        name: Proton5T
        species: proton 
        cent_freq: 212.882            # Center frequency in MHz   (float)
        mod_freq: 400.0             # Frequency modulation in kHz   (float)
        power: 200.0                # RF power in mV  (float)
        sweep_file: tri             # Sweep type (tri is standard triangle; if file name that exists, reads for arbitrary)
    Proton4.87T:
        name: Proton4.87T
        species: proton 
        cent_freq: 207.38            # Center frequency in MHz   (float)
        mod_freq: 400.0             # Frequency modulation in kHz   (float)
        power: 200.0                # RF power in mV  (float)
        sweep_file: tri             # Sweep type (tri is standard triangle; if file name that exists, reads for arbitrary)
    Deuteron5T:
        name: Deuteron5T
        species: deuteron
        cent_freq: 32.7       
        mod_freq: 400.0        
        power: 200.0      
        sweep_file: tri   
    Deuteron4.87T:
        name: Deuteron4.87T
        species: deuteron
        cent_freq: 31.83       
        mod_freq: 400.0        
        power: 200.0      
        sweep_file: tri 
    Crystal:
        name: Crystal
        species: proton
        cent_freq: 224.5       
        mod_freq: 400.0        
        power: 200.0      
        sweep_file: tri 
     
settings:
    default_channel: Proton5T     # Default from channels listed above
    daq_type: NIDAQ             # Select DAQ mode (FPGA, NIDAQ or Test)
    test_signal: app/d_signal_event.txt  # signal to use for test mode
    event_dir: data             # Directory to put eventfiles in, relative to main.py or absolute
    te_dir: te                  # Directory to put te files in, relative to main.py or absolute
    log_dir: log                # Directory to put log files in, relative to main.py or absolute
    ss_dir: screens               # Directory to put screenshots files in, screenshots not taken if False
    session_file: session
    history_file: history
    steps: 512                  # Frequency points per sweep (must match for test sweeps, set to 512 otherwise)
    num_per_chunk: 64           # Number of sweeps per chunk (IntSweepCycle from FPGA manual)
    tune_per_chunk:  32         # Number of sweeps per chunk to take in tune mode
    epics_settings:
        enable: false       # If false, doesn't attempt to contact EPICS server
        monitor_time: 5            # Time between calls to get EPICS data
        timeout: 1
        epics_temp: TGT:PT12:Bath_Top_T      # EPICS channel of temp to use as default 
        beam_current: scaler_calc1      # EPICS channel of beam current
        current_threshold: 3     # Current in nA at which we consider beam to be on
    fpga_settings:    
        ip: 192.168.1.77        # Device IP address (str)
        port: 1028              # Device port  (int)
        tcp_buffer: 1460        # Default TCP buffer size  (int)
        dwell: 10               # Settle time in usec between frequency switch and ADC read (int) (was 10)
        per_point: 2            # Samples taken and averaged at each frequency point of a sweep (int)
        timeout_run: 20         # TCP timeout for running sweeps
        timeout_tune: 1         # TCP timeout for tune
        timeout_check: 1        # TCP timeout for check
        timeout_udp: 1          # Timeout for udp commands
        adc_drate1: true        # ADC data rate settings, see manual
        adc_drate0: true
        adc_fpath: false        # ADC fpath setting, see manual
        phase_cal: 211692085    # Conversion int to divide phase ADC values by to get max of 1
        diode_cal: 829421       # Conversion int to divide diode ADC values by to get max of 1
#       #phase_cal: 1672129    # Conversion int to divide phase ADC values by to get max of 1
#       #diode_cal: 1672129       # Conversion int to divide diode ADC values by to get max of 1
        test_freqs: false       # Send test frequencies to FPGA
        adc_test: false         # ADC test mode flag
        phase_adc_number: 2         # Which ADC channel will be phase signal? 1 or 2
    nidaq_settings:
        phase_chan: Dev2/ai0
        diode_chan: Dev2/ai1
        ao_chan: Dev2/ao0
        pretris: 10             # Number of pretriangles
        time_per_pt: 29         # Dwell time at frequency, usecs
        settling_ratio: 0.5     # Where in the dwell time the read occurs (0 to 1)     
    RS_settings:
        ip: 192.168.1.5              # R&S RF generator IP
        port: 5025 
        timeout: 2              # Telnet timeout in secs
    uWave_settings:
        enable: true         # Turn on uWave controls
        monitor_time: .4         # How long to wait between reading frequency when on monitor in s
        counter:
            ip: 129.57.160.5       # GPIB IP
            port: 1234
            timeout: 4              # Telnet timeout in secs
            addr: 19        # EIP 588C frequency counter GPIB address
            cent_freq: 136.6        # Microwave counter center frequency in GHz
            band: 3                 # Microwave counter band
            subband: 8              # Microwwave counter subband
            rate: 500               # Counter sample rate in ms
        power_meter:
            ip: 129.57.160.11       # Serial interface IP
            port: 23
            timeout: 2              # Telnet timeout in secs
            freq: 140               # Power meter set freq in GHz
        lj-ip: 129.57.160.6     # LabJack device IP
        relay-ip: 129.57.161.12     # Relay device IP, 129.57.161.123 is pt-eio-relay
        eio_method: 'ip'            # 'ip' or 'lj'
    temp_settings:
        enable: false           # Turn on or off temp monitor tab
        ip: 129.57.160.6       # R&S supply IP   
        monitor_time: 60       # seconds
    shim_settings:
        enable: false
        ip: 129.57.160.4       # R&S supply IP
        port: 5025 
        timeout: 2  
        line_resistance: 0.3     # Ohms
    fm_settings:
        enable: false
        ip: 129.57.160.12       # R&S supply IP
        port: 1234
        timeout: 2     
        addr: 10                # GPIB address    
    analysis:
        base_def: 0             # index of default baseline subtraction method      
        sub_def: 0              # index of default fit subtraction method   
        res_def: 0              # index of default results analysis method   
        wings:                  # default bounds for fit wings, must be four numbers between 0 and 1
            - 0.01
            - 0.30
            - 0.70
            - 0.99
        sum_range:              # default bounds for range integration option
            - 0.35
            - 0.65
        d_fit_params:           # initial parameters for Dulya fits
            A : 0.03
            G : -0.003
            r : 0.99
            wQ : 0.025
            wL : 31.83
            eta : 0.09
            xi : -0.1
epics_reads:                    # EPICS channels to read: key is channel name, value is string to display
    TGT:PT12:Bath_LL: Bath Level
    TGT:PT12:VaporPressure_T: Vapor Temp (K)
    TGT:PT12:Bath_Top_T: Bath Top (K)
    TGT:PT12:Bath_Bottom_T: Bath Bottom (K)
    TGT:PT12:NMR_T: Tank Temp (K)
    TGT:PT12:Bath_HTR_lvl: Bath Heater
    TGT:PT12:Fridge_F: Main Flow (slpm)
    TGT:PT12:Separator_F: Sep Flow (slpm)
    B_SOL:MPS:I_ZFCT: Solenoid Current (A)
    scaler_calc1: Beam Current (nA)
    TGT:PT12:Target_Dose: Dose (e/cm^2)
epics_writes:                   # Dict of channels to write, key is channel, value is attribute of Event class 
    TGT:PT12:Polarization: pol 
    TGT:PT12:NMR_Area: area
    TGT:PT12:NMR_CC: cc
    TGT:PT12:NMR_Time: stop_stamp  
    TGT:PT12:uwave_Freq: uwave_freq
    TGT:PT12:uwave_Power: uwave_power
    TGT:PT12:ShimCurrent_A: shimA
    TGT:PT12:ShimCurrent_B: shimB
    TGT:PT12:ShimCurrent_C: shimC
    TGT:PT12:ShimCurrent_D: shimD