channels:
  proton:
    cent_freq: 213.0
    mod_freq: 50.0
    species: proton
    sweep_file: standard_sweep.txt
epics_reads: {}
epics_writes: {}
settings:
  compare_tab:
    enable: false
  daq_type: UDP
  default_channel: proton
  event_dir: ./data
  explorer:
    enable: false
  fm_settings:
    enable: false
  history_file: history
  log_dir: ./log
  num_per_chunk: 10
  session_file: session
  shim_settings:
    enable: false
  ss_dir: ''
  steps: 100
  temp_settings:
    enable: false
